/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Billing.java
 *
 * Created on Oct 26, 2016, 10:24:20 PM
 */
package javaapplication4;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Virendra
 */
public class Billing extends javax.swing.JFrame {
    
    public double famount;
    public int quantity;
    public String items;
    public String vegetables="";
    public String fruits="";
    public String cosmetics="";
    public String stationary="";
    public String clothes="";



    /** Creates new form Billing */
    public Billing() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jButton1.setText("Generate Bill");
        jButton1.setToolTipText("CLICK TO GENERATE BILL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("Mobile No");

        jLabel5.setText("Amount");

        jLabel6.setText("Vegges");

        jLabel7.setText("Fruits");

        jLabel8.setText("Cosmetics");

        jLabel9.setText("Stationaary");

        jLabel10.setText("Clothes");

        jButton2.setText("Back");
        jButton2.setToolTipText("CLICK TO GO TO HOMEPAGE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField4.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Serif", 1, 24));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Billing Panel");

        jTextField3.setText("0");

        jTextField6.setText("0");

        jTextField7.setText("0");

        jTextField8.setText("0");

        jTextField9.setText("0");

        jButton3.setText("Add ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Add");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Remove");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Remove");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Remove");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Remove");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Remove");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel3.setText("Total Quantity");

        jTextField10.setEnabled(false);

        jLabel13.setText("Quantity");

        jLabel4.setText("Choose Item");

        jLabel11.setText("Choose Item");

        jLabel14.setText("Choose Item");

        jLabel15.setText("Choose Item");

        jLabel16.setText("Choose Item");

        jLabel17.setText("Item Price");

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem2.setText("About");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(221, 221, 221)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(68, 68, 68)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(73, 73, 73)
                                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(73, 73, 73)
                                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(35, 35, 35)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(35, 35, 35)
                                            .addComponent(jButton8)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jButton9))))
                            .addComponent(jLabel17)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(231, 231, 231)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(80, 80, 80)
                .addComponent(jButton2)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 993, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel2))
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addComponent(jLabel13))
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton3)
                                .addComponent(jButton8)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton4)
                                    .addComponent(jButton9))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton5)
                                .addComponent(jButton10)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton12)
                                .addComponent(jButton6)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton7)
                                .addComponent(jButton11)))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

        try {
                      
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket", "root", "smhs");

            Statement stmt = (Statement) con.createStatement();
            Statement stmt1 = (Statement) con.createStatement();
            Statement stmt2 = (Statement) con.createStatement();
            Statement stmt3 = (Statement) con.createStatement();
            Statement stmt4 = (Statement) con.createStatement();

            String sql = "Select itemname from stocks where itemcategory='Vegetables'";
            String sql1 = "Select itemname from stocks where itemcategory='Fruits'";
            String sql2 = "Select itemname from stocks where itemcategory='Cosmetics'";
            String sql3 = "Select itemname from stocks where itemcategory='Stationary'";
            String sql4 = "Select itemname from stocks where itemcategory='Clothes'";

            ResultSet rs = stmt.executeQuery(sql);
            ResultSet rs1 = stmt1.executeQuery(sql1);
            ResultSet rs2 = stmt2.executeQuery(sql2);
            ResultSet rs3 = stmt3.executeQuery(sql3);
            ResultSet rs4 = stmt4.executeQuery(sql4);

            while (rs.next() && rs1.next() && rs2.next() && rs3.next() && rs4.next()) {

                String itemname = rs.getString("itemname");                
                String itemname2 = rs1.getString("itemname");
                String itemname3 = rs2.getString("itemname");
                String itemname4 = rs3.getString("itemname");
                String itemname5 = rs4.getString("itemname");
                
                jComboBox1.addItem(itemname);
                jComboBox2.addItem(itemname2);
                jComboBox3.addItem(itemname3);
                jComboBox4.addItem(itemname4);
                jComboBox5.addItem(itemname5);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_formWindowActivated

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket", "root", "smhs");
            Statement stmt = (Statement) con.createStatement();

            String name = jTextField1.getText();
            String mobileno = jTextField2.getText();
            quantity = Integer.parseInt(jTextField10.getText());
            Date dateandtime = new Date();
            String query = "Insert into history values('" + name + "','" + quantity + "','" + famount + "','" + mobileno + "','" + dateandtime + "','" + vegetables+ "','" + fruits+"','" + cosmetics+"','" + stationary+"','" + clothes+ "');";
            stmt.executeUpdate(query);} 
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        JOptionPane.showMessageDialog(this,"Please Collect Rs. "+famount+" from the customer. ");
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFrame Homepage = new Homepage();
        Homepage.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int i;
        i=Integer.parseInt(jTextField3.getText());
        String v = jComboBox1.getSelectedItem().toString();
        int itemprice=0;
        int itemquantity = 0;

        try {
        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket", "root", "smhs");
        Statement stmt = (Statement) con.createStatement();
        Statement stmt1 = (Statement) con.createStatement();
        String sql = "Select * from stocks where itemname='"+v+"';";
           
        ResultSet rs = stmt.executeQuery(sql);
       
        while (rs.next()) {
             itemprice = rs.getInt("itemprice");
             itemquantity = rs.getInt("itemquantity");}

        itemquantity=itemquantity-i;
        String sql1 = "Update stocks set itemquantity='"+itemquantity+"' where itemname='"+v+"'";
        stmt1.executeUpdate(sql1);
    
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());}
        
        jLabel4.setText(Integer.toString(itemprice));
        famount=(i*itemprice)+famount;
        jTextField4.setText(Double.toString(famount));
        vegetables = vegetables+" "+v;
        quantity=quantity+i;
        jTextField10.setText(Integer.toString(quantity));
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int i;
        i=Integer.parseInt(jTextField6.getText());
        String f = jComboBox2.getSelectedItem().toString();
        int itemquantity = 0;
        int itemprice=0;

        try {
        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket", "root", "smhs");
        Statement stmt = (Statement) con.createStatement();
        Statement stmt1 = (Statement) con.createStatement();

            String sql = "Select * from stocks where itemname='"+f+"'";

        ResultSet rs = stmt.executeQuery(sql);
        while (rs.next()) {
            itemquantity = rs.getInt("itemquantity");
             itemprice = rs.getInt("itemprice");
        }
        itemquantity=itemquantity-i;
        String sql1 = "Update stocks set itemquantity='"+itemquantity+"' where itemname='"+f+"'";
        stmt1.executeUpdate(sql1);
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
         }

        jLabel11.setText(Integer.toString(itemprice));
        famount=(i*itemprice)+famount;
        jTextField4.setText(Double.toString(famount));
        fruits= fruits+" "+f;
        quantity=quantity+i;        
        jTextField10.setText(Integer.toString(quantity));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int i;
        i=Integer.parseInt(jTextField7.getText());
        String c = jComboBox3.getSelectedItem().toString();
        int itemquantity = 0;
        int itemprice=0;

        try {
        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket", "root", "smhs");
        Statement stmt = (Statement) con.createStatement();
        Statement stmt1 = (Statement) con.createStatement();
        String sql = "Select * from stocks where itemname='"+c+"'";

        ResultSet rs = stmt.executeQuery(sql);
        while (rs.next()) {
            itemquantity = rs.getInt("itemquantity");
             itemprice = rs.getInt("itemprice");
        }
        itemquantity=itemquantity-i;
        String sql1 = "Update stocks set itemquantity='"+itemquantity+"' where itemname='"+c+"'";
        stmt1.executeUpdate(sql1);
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
        }

        jLabel14.setText(Integer.toString(itemprice));
        famount=(i*itemprice)+famount;
        jTextField4.setText(Double.toString(famount));
        cosmetics = cosmetics+" "+c;
        quantity=quantity+i;
        jTextField10.setText(Integer.toString(quantity));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int i;
        i=Integer.parseInt(jTextField8.getText());
        String s = jComboBox4.getSelectedItem().toString();
        int itemquantity = 0;
        int itemprice=0;

        try {
        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket", "root", "smhs");
        Statement stmt = (Statement) con.createStatement();
        Statement stmt1 = (Statement) con.createStatement();
        String sql = "Select * from stocks where itemname='"+s+"'";

        ResultSet rs = stmt.executeQuery(sql);
        while (rs.next()) {
            itemquantity = rs.getInt("itemquantity");
             itemprice = rs.getInt("itemprice");
        }
        itemquantity=itemquantity-i;
        String sql1 = "Update stocks set itemquantity='"+itemquantity+"' where itemname='"+s+"'";
        stmt1.executeUpdate(sql1);
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
        }

        jLabel15.setText(Integer.toString(itemprice));
        famount=(i*itemprice)+famount;
        jTextField4.setText(Double.toString(famount));
        stationary = stationary+" "+s;
        quantity=quantity+i;
        jTextField10.setText(Integer.toString(quantity));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int i;
        i=Integer.parseInt(jTextField9.getText());
        String cl = jComboBox5.getSelectedItem().toString();
        int itemquantity = 0;
        int itemprice=0;

        try {
        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket", "root", "smhs");
        Statement stmt = (Statement) con.createStatement();
        Statement stmt1 = (Statement) con.createStatement();
        String sql = "Select * from stocks where itemname='"+cl+"'";

        ResultSet rs = stmt.executeQuery(sql);
        while (rs.next()) {
            itemquantity = rs.getInt("itemquantity");
             itemprice = rs.getInt("itemprice");
        }
        itemquantity=itemquantity-i;
        String sql1 = "Update stocks set itemquantity='"+itemquantity+"' where itemname='"+cl+"'";
        stmt1.executeUpdate(sql1);
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
        }

        jLabel16.setText(Integer.toString(itemprice));
        famount=(i*itemprice)+famount;
        jTextField4.setText(Double.toString(famount));
        clothes = clothes+" "+cl;
        quantity=quantity+i;
        jTextField10.setText(Integer.toString(quantity));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int i;
        i=Integer.parseInt(jTextField3.getText());
        String v = jComboBox1.getSelectedItem().toString();
        int itemprice=0;
        int itemquantity = 0;

        try {
        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket", "root", "smhs");
        Statement stmt = (Statement) con.createStatement();
        Statement stmt1 = (Statement) con.createStatement();
        String sql = "Select * from stocks where itemname='"+v+"';";
            
        ResultSet rs = stmt.executeQuery(sql);
       
        while (rs.next()) {
             itemprice = rs.getInt("itemprice");
             itemquantity = rs.getInt("itemquantity");
        
        }
        itemquantity=itemquantity+i;
        String sql1 = "Update stocks set itemquantity='"+itemquantity+"' where itemname='"+v+"'";
        stmt1.executeUpdate(sql1);

        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
        }

        famount=famount-(i*itemprice);
        jTextField4.setText(Double.toString(famount));
        vegetables = vegetables.replaceAll(" "+v, "");
        quantity=quantity-i;
        jTextField10.setText(Integer.toString(quantity));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int i;
        i=Integer.parseInt(jTextField6.getText());
        String f = jComboBox2.getSelectedItem().toString();
        int itemquantity = 0;
        int itemprice=0;

        try {
        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket", "root", "smhs");
        Statement stmt = (Statement) con.createStatement();
        Statement stmt1 = (Statement) con.createStatement();

            String sql = "Select * from stocks where itemname='"+f+"'";

        ResultSet rs = stmt.executeQuery(sql);
        while (rs.next()) {
            itemquantity = rs.getInt("itemquantity");
             itemprice = rs.getInt("itemprice");
        }
        itemquantity=itemquantity+i;
        String sql1 = "Update stocks set itemquantity='"+itemquantity+"' where itemname='"+f+"'";
        stmt1.executeUpdate(sql1);
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
        }

        famount=famount-(i*itemprice);
        jTextField4.setText(Double.toString(famount));
        fruits = fruits.replaceAll(" "+f, "");
        quantity=quantity-i;
        jTextField10.setText(Integer.toString(quantity));
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int i;
        i=Integer.parseInt(jTextField7.getText());
        String c = jComboBox3.getSelectedItem().toString();
        int itemquantity = 0;
        int itemprice=0;

        try {
        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket", "root", "smhs");
        Statement stmt = (Statement) con.createStatement();
        Statement stmt1 = (Statement) con.createStatement();
            String sql = "Select * from stocks where itemname='"+c+"'";

        ResultSet rs = stmt.executeQuery(sql);
        while (rs.next()) {
            itemquantity = rs.getInt("itemquantity");
             itemprice = rs.getInt("itemprice");
        }
        itemquantity=itemquantity+i;
        String sql1 = "Update stocks set itemquantity='"+itemquantity+"' where itemname='"+c+"'";
        stmt1.executeUpdate(sql1);
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
        }

        famount=famount-(i*itemprice);
        jTextField4.setText(Double.toString(famount));
        cosmetics = cosmetics.replaceAll(" "+c, "");
        quantity=quantity-i;
        jTextField10.setText(Integer.toString(quantity));
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        int i;
        i=Integer.parseInt(jTextField8.getText());
        String s = jComboBox4.getSelectedItem().toString();
        int itemquantity = 0;
        int itemprice=0;

        try {
        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket", "root", "smhs");
        Statement stmt = (Statement) con.createStatement();
        Statement stmt1 = (Statement) con.createStatement();
        String sql = "Select * from stocks where itemname='"+s+"'";

        ResultSet rs = stmt.executeQuery(sql);
        while (rs.next()) {
            itemquantity = rs.getInt("itemquantity");
             itemprice = rs.getInt("itemprice");
        }
        itemquantity=itemquantity+i;
        String sql1 = "Update stocks set itemquantity='"+itemquantity+"' where itemname='"+s+"'";
        stmt1.executeUpdate(sql1);
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
        }

        famount=famount-(i*itemprice);
        jTextField4.setText(Double.toString(famount));
        stationary = stationary.replaceAll(" "+s, "");
        quantity=quantity-i;
        jTextField10.setText(Integer.toString(quantity));
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        int i;
        i=Integer.parseInt(jTextField9.getText());
        String cl = jComboBox5.getSelectedItem().toString();
        int itemquantity = 0;
        int itemprice=0;

        try {
        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket", "root", "smhs");
        Statement stmt = (Statement) con.createStatement();
        Statement stmt1 = (Statement) con.createStatement();
            String sql = "Select * from stocks where itemname='"+cl+"'";

        ResultSet rs = stmt.executeQuery(sql);
        while (rs.next()) {
            itemquantity = rs.getInt("itemquantity");
             itemprice = rs.getInt("itemprice");
        }
        itemquantity=itemquantity+i;
        String sql1 = "Update stocks set itemquantity='"+itemquantity+"' where itemname='"+cl+"'";
        stmt1.executeUpdate(sql1);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }

        famount=famount-(i*itemprice);
        jTextField4.setText(Double.toString(famount));
        clothes = clothes.replaceAll(" "+cl, "");
        quantity=quantity-i;
        jTextField10.setText(Integer.toString(quantity));
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JFrame About = new About();
        About.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
